name: json_dynamic_widget_builder
description: An application to allow for building dynamic widgets via JSON in a WYSIWYG editor.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_builder

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.5.1
  form_validation: ^1.0.1
  json_class: ^1.0.6
  json_conditional: ^1.0.3
  json_dynamic_widget: ^1.2.0+2
  json_schema: ^2.2.1
  json_theme: ^1.4.1
  logging: ^0.11.4
  meta: ^1.1.8
  provider: 4.3.2+2
  sembast: ^2.4.8
  sembast_web: ^1.2.0
  tinycolor: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  json_dynamic_widget:
    path: ../json_dynamic_widget
#   json_theme:
#     path: ../json_theme

flutter:
  uses-material-design: true
